<a href="https://colab.research.google.com/github/Nico-ASL/Data-sciense.python-2026/blob/main/Inmueble_CDMX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pandas Alura
#Importando base de datos

In [1]:
import pandas as pd

url = "https://gist.githubusercontent.com/ahcamachod/a572cfcc2527046db93101f88011b26e/raw/ffb13f45a79d31223e645611a119397dd127ee3c/alquiler.csv"

datos = pd.read_csv(url)

datos.head()

  Tipo;Colonia;Habitaciones;Garages;Suites;Area;Valor;Condominio;Impuesto
0      Cocineta;Condesa;1;0;0;40;5950.0;1750.0;210.0
1                   Casa;Polanco;2;0;1;100;24500.0;;
2  Conjunto Comercial/Sala;Santa Fe;0;4;0;150;182...
3  Departamento;Centro Histórico;1;0;0;15;2800.0;...
4      Departamento;Del Valle;1;0;0;48;2800.0;805.0;

In [2]:
datos = pd.read_csv(url, sep=';')

datos.head()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN

In [4]:
datos = datos = pd.read_csv(url, sep=';')

datos.head()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN

##**Exploración de datos**

In [5]:
datos.shape

(25121, 9)

In [6]:
datos.columns

Index(['Tipo', 'Colonia', 'Habitaciones', 'Garages', 'Suites', 'Area', 'Valor',
       'Condominio', 'Impuesto'],
      dtype='object')

In [7]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25121 entries, 0 to 25120
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tipo          25121 non-null  object
 1   Colonia       25121 non-null  object
 2   Habitaciones  25121 non-null  int64
 3   Garages       25121 non-null  int64
 4   Suites        25121 non-null  int64
 5   Area          25121 non-null  int64
 6   Valor         25107 non-null  float64
 7   Condominio    22495 non-null  float64
 8   Impuesto      18037 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 1.7+ MB

In [8]:
datos['Tipo']

0                       Cocineta
1                           Casa
2        Conjunto Comercial/Sala
3                   Departamento
4                   Departamento
                  ...
25116    Cochera/Estacionamiento
25117                   Cocineta
25118               Departamento
25119               Departamento
25120    Conjunto Comercial/Sala
Name: Tipo, Length: 25121, dtype: object

In [10]:
datos[['Habitaciones','Valor']]

       Habitaciones    Valor
0                 1   5950.0
1                 2  24500.0
2                 0  18200.0
3                 1   2800.0
4                 1   2800.0
...             ...      ...
25116             0  49000.0
25117             0   2800.0
25118             2   4900.0
25119             2  10500.0
25120             0  22750.0

[25121 rows x 2 columns]

In [11]:
datos.groupby('Tipo')['Valor'].mean()

Tipo
Casa                           31453.177064
Casa Comercial                 54735.841584
Casa de Condominio             51428.609836
Casa de Vecindad                5961.740506
Cochera/Estacionamiento         6995.454545
Cocineta                        4425.856061
Conjunto Comercial/Sala        57675.214550
Departamento                   18683.269431
Departamento en Hotel          16285.430769
Edificio Completo             409418.080645
Estudio                         8400.000000
Galpón/Depósito/Almacén       299984.140138
Hotel                          87500.000000
Industria                     420000.000000
Loft                            9924.526316
Loteo/Condominio               92166.666667
Posada/Chalé                    5180.000000
Rancho                         38014.375000
Terreno Estándar              135364.444444
Tienda en Centro Comercial     32556.785714
Tienda/Salón                   56263.544252
Name: Valor, dtype: float64

In [12]:
datos['Tipo'].value_counts(normalize=True) * 100

Tipo
Departamento                  58.771546
Conjunto Comercial/Sala       22.614546
Tienda/Salón                   4.370845
Cocineta                       2.890012
Casa de Condominio             2.428247
Casa                           2.169500
Departamento en Hotel          1.811234
Galpón/Depósito/Almacén        1.150432
Edificio Completo              0.863819
Casa Comercial                 0.804108
Tienda en Centro Comercial     0.784204
Casa de Vecindad               0.628956
Cochera/Estacionamiento        0.306516
Terreno Estándar               0.179133
Loft                           0.151268
Rancho                         0.031846
Estudio                        0.015923
Loteo/Condominio               0.011942
Hotel                          0.007961
Posada/Chalé                   0.003981
Industria                      0.003981
Name: proportion, dtype: float64

In [13]:
datos.isnull().sum()

Tipo               0
Colonia            0
Habitaciones       0
Garages            0
Suites             0
Area               0
Valor             14
Condominio      2626
Impuesto        7084
dtype: int64

In [14]:
datos['Condominio'] = datos['Condominio'].fillna(0)

In [15]:
datos = datos[~((datos['Tipo'] == 'Departamento') & (datos['Valor'] == 0))]

In [16]:
datos = datos[~((datos['Tipo'] == 'Departamento') & (datos['Condominio'] == 0))]

In [17]:
datos[(datos['Tipo'] == 'Departamento') & (datos['Valor'] == 0)]

Empty DataFrame
Columns: [Tipo, Colonia, Habitaciones, Garages, Suites, Area, Valor, Condominio, Impuesto]
Index: []

In [18]:
datos[(datos['Tipo'] == 'Departamento') & (datos['Condominio'] == 0)]

Empty DataFrame
Columns: [Tipo, Colonia, Habitaciones, Garages, Suites, Area, Valor, Condominio, Impuesto]
Index: []

In [19]:
datos.shape

(24628, 9)

In [20]:
filtro1 = (datos['Tipo'] == 'Departamento') & (datos['Habitaciones'] == 1) & (datos['Valor'] < 4200)

In [21]:
filtro2 = (datos['Tipo'] == 'Departamento') & (datos['Habitaciones'] >= 2) & (datos['Valor'] < 10500) & (datos['Area'] > 70)

In [23]:
datos_filtrados = datos[filtro1 | filtro2]

In [24]:
datos_filtrados.head()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
14,Departamento,Narvarte,2,1,0,110,6650.0,2450.0,483.0
16,Departamento,Narvarte,2,1,0,78,7000.0,2450.0,NaN
19,Departamento,Narvarte,1,0,0,48,2625.0,2702.0,87.5

In [25]:
datos.to_csv('datos_limpios.csv', sep=';', index=False)

In [26]:
datos_filtrados.to_csv('datos_filtrados.csv', sep=';', index=False)

In [28]:
datos['valor_mensual'] = datos['Valor'] + datos['Condominio']

In [29]:
datos['valor_anual'] = datos['Impuesto'] + 12 * datos['valor_mensual']

In [30]:
datos.head()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto,valor_mensual,valor_anual
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0,7700.0,92610.0
1,Casa,Polanco,2,0,1,100,24500.0,0.0,NaN,24500.0,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5,32270.0,391128.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0,4165.0,50050.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN,3605.0,NaN

In [34]:
datos.columns

Index(['Tipo', 'Colonia', 'Habitaciones', 'Garages', 'Suites', 'Area', 'Valor',
       'Condominio', 'Impuesto', 'valor_mensual', 'valor_anual'],
      dtype='object')

In [35]:
datos['Descripcion'] = (
    datos['Tipo'] + ' en ' + datos['Colonia'] +
    ' con ' + datos['Habitaciones'].astype(str) +
    ' habitaciones y ' + datos['Garages'].astype(str) + ' garages'
)

In [36]:
datos['Tiene_suite'] = datos['Suites'] > 0

In [37]:
datos['Tiene_suite'] = (datos['Suites'] > 0).map({True: 'Sí', False: 'No'})

In [38]:
datos[['Descripcion', 'Tiene_suite']].head()

                                         Descripcion Tiene_suite
0  Cocineta en Condesa con 1 habitaciones y 0 gar...          No
1     Casa en Polanco con 2 habitaciones y 0 garages          Sí
2  Conjunto Comercial/Sala en Santa Fe con 0 habi...          No
3  Departamento en Centro Histórico con 1 habitac...          No
4  Departamento en Del Valle con 1 habitaciones y...          No